CHARACTERS = [
    # ── CANDIDATOS A PRESIDENTE ──────────────────────────────────────────────
    {
        "name": "Iván Cepeda",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Perfil_Iv%C3%A1n_Cepeda_%28cropped%29.jpg/330px-Perfil_Iv%C3%A1n_Cepeda_%28cropped%29.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Pacto Histórico",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": True,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Pasó a segunda vuelta con 40.9%. Hijo del activista Manuel Cepeda, asesinado en 1994.",
    },
    {
        "name": "Claudia López",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Claudia_Lopez_H_26.jpg/330px-Claudia_Lopez_H_26.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Con Claudia, Imparables",
        "gender": "female",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": True,
        "fue_presidente": False,
        "fun_fact": "Se quemó en primera vuelta. Fue la primera alcaldesa de Bogotá (2020-2023).",
    },
    {
        "name": "Abelardo de la Espriella",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Abelardo_de_la_Espriella_2025.jpg/330px-Abelardo_de_la_Espriella_2025.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Defensores de la Patria",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": True,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": True,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Pasó a segunda vuelta con 43.7%. Abogado penalista famoso por defender casos de alto perfil.",
    },
    {
        "name": "Sergio Fajardo",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/SergioFajardo.jpg/330px-SergioFajardo.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Dignidad & Compromiso",
        "gender": "male",
        "hair_color": "white",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "light",
        "paso_segunda_vuelta": False,
        "fue_alcalde": True,
        "fue_presidente": False,
        "fun_fact": "Se quemó con 4.25%. Matemático y exalcalde de Medellín. Va por su tercera candidatura presidencial.",
    },
    {
        "name": "Paloma Valencia",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Discurso_Paloma_Valencia.jpg/330px-Discurso_Paloma_Valencia.jpg",
        "photo_position": "center 20%",
        "role": "Presidente",
        "party": "Centro Democrático",
        "gender": "female",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "light",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó con 6.92%. Nieta del expresidente Guillermo León Valencia. Senadora y columnista.",
    },
    {
        "name": "Roy Barreras",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/20250609_Comision_Procesos_Electorales-Juan_Cano01043.jpg/330px-20250609_Comision_Procesos_Electorales-Juan_Cano01043.jpg",
        "photo_position": "center 15%",
        "role": "Presidente",
        "party": "La Fuerza",
        "gender": "male",
        "hair_color": "white",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó en primera vuelta. Médico, poeta y escritor. Fue embajador en Reino Unido.",
    },
    {
        "name": "Mauricio Lizcano",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mauricio_Lizcano_2023.jpg/330px-Mauricio_Lizcano_2023.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Firme con Lizcano",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó en primera vuelta. Exministro de las TIC que impulsó la conectividad rural.",
    },
    {
        "name": "Santiago Botero",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Santiago_Botero_Jaramillo.jpg/330px-Santiago_Botero_Jaramillo.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Romper el Sistema",
        "gender": "male",
        "hair_color": "brown",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": True,
        "has_mustache": True,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó en primera vuelta. Empresario que nunca había participado en política antes de 2026.",
    },

    # ── PRESIDENTES (en ejercicio / ex) ──────────────────────────────────────
    {
        "name": "Gustavo Petro",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Foto_Oficial_Presidente_Gustavo_Petro_%283x4_cropped%29.jpg/330px-Foto_Oficial_Presidente_Gustavo_Petro_%283x4_cropped%29.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Colombia Humana / Pacto Histórico",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": True,
        "fue_presidente": True,
        "fun_fact": "Presidente en ejercicio (2022–2026). Fue guerrillero del M-19. Tiene ciudadanía italiana.",
    },
    {
        "name": "Álvaro Uribe",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/%C3%81lvaro_Uribe_%28cropped%29.jpg/330px-%C3%81lvaro_Uribe_%28cropped%29.jpg",
        "photo_position": "center top",
        "role": "Presidente",
        "party": "Centro Democrático",
        "gender": "male",
        "hair_color": "white",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": True,
        "fue_presidente": True,
        "fun_fact": "Expresidente (2002–2010). A los 28 años dirigió la Aeronáutica Civil. Estudió en Harvard y Oxford.",
    },

    # ── CANDIDATOS A VICEPRESIDENTE ──────────────────────────────────────────
    {
        "name": "Aída Quilcué",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Aida_Quilcu%C3%A9_2024.jpg/330px-Aida_Quilcu%C3%A9_2024.jpg",
        "photo_position": "center top",
        "role": "Vicepresidente",
        "party": "Pacto Histórico",
        "gender": "female",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "dark",
        "paso_segunda_vuelta": True,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Lideresa del pueblo Nasa. Fórmula de Cepeda. Primera candidata indígena a la vicepresidencia.",
    },
    {
        "name": "Juan Daniel Oviedo",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Juan_Daniel_Oviedo_2025.jpg/330px-Juan_Daniel_Oviedo_2025.jpg",
        "photo_position": "center top",
        "role": "Vicepresidente",
        "party": "Centro Democrático",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": True,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó con Paloma Valencia. Exdirector del DANE. Popularizó las cifras de pobreza en Colombia.",
    },
    {
        "name": "José Manuel Restrepo",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Jos%C3%A9_Manuel_Restrepo.jpg/330px-Jos%C3%A9_Manuel_Restrepo.jpg",
        "photo_position": "center top",
        "role": "Vicepresidente",
        "party": "Defensores de la Patria",
        "gender": "male",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "light",
        "paso_segunda_vuelta": True,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Fórmula de De la Espriella. Exministro de Hacienda y rector de la Universidad del Rosario.",
    },
    {
        "name": "Edna Bonilla",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Edna_Bonilla.jpg/330px-Edna_Bonilla.jpg",
        "photo_position": "center top",
        "role": "Vicepresidente",
        "party": "Dignidad & Compromiso",
        "gender": "female",
        "hair_color": "black",
        "hair_type": "curly",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "dark",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó con Fajardo. Economista afrocolombiana y exdirectora del Departamento Nacional de Planeación.",
    },
    {
        "name": "Martha Lucía Zamora",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/MarthaZamora.jpg/330px-MarthaZamora.jpg",
        "photo_position": "center top",
        "role": "Vicepresidente",
        "party": "La Fuerza",
        "gender": "female",
        "hair_color": "black",
        "hair_type": "straight",
        "eye_color": "brown",
        "has_glasses": False,
        "has_hat": False,
        "has_beard": False,
        "has_mustache": False,
        "skin_tone": "medium",
        "paso_segunda_vuelta": False,
        "fue_alcalde": False,
        "fue_presidente": False,
        "fun_fact": "Se quemó con Barreras. Abogada y exdirectora de la Fiscalía General de la Nación.",
    },
]

VALID_ATTRIBUTES = {
    "role":                ["Presidente", "Vicepresidente"],
    "gender":              ["male", "female"],
    "hair_color":          ["black", "brown", "blonde", "red", "white", "none"],
    "hair_type":           ["straight", "curly", "bald"],
    "eye_color":           ["brown", "blue", "green"],
    "has_glasses":         [True, False],
    "has_hat":             [True, False],
    "has_beard":           [True, False],
    "has_mustache":        [True, False],
    "skin_tone":           ["light", "medium", "dark"],
    "paso_segunda_vuelta": [True, False],
    "fue_alcalde":         [True, False],
    "fue_presidente":      [True, False],
}

CHARACTER_NAMES = [c["name"] for c in CHARACTERS]


def get_character(name: str) -> dict | None:
    return next((c for c in CHARACTERS if c["name"] == name), None)


def get_question_templates() -> dict:
    return {
        "role": {
            "Presidente":     "¿Es candidato/a a Presidente?",
            "Vicepresidente": "¿Es candidato/a a Vicepresidente?",
        },
        "gender": {
            "male":   "¿Es hombre?",
            "female": "¿Es mujer?",
        },
        "hair_color": {
            "black":  "¿Tiene el pelo negro?",
            "brown":  "¿Tiene el pelo café?",
            "blonde": "¿Tiene el pelo rubio?",
            "red":    "¿Tiene el pelo rojo?",
            "white":  "¿Tiene el pelo blanco/canoso?",
            "none":   "¿Está calvo/a?",
        },
        "hair_type": {
            "straight": "¿Tiene el pelo liso?",
            "curly":    "¿Tiene el pelo rizado?",
            "bald":     "¿Está completamente calvo/a?",
        },
        "eye_color": {
            "brown": "¿Tiene ojos cafés?",
            "blue":  "¿Tiene ojos azules?",
            "green": "¿Tiene ojos verdes?",
        },
        "has_glasses": {
            True:  "¿Lleva gafas?",
            False: "¿No lleva gafas?",
        },
        "has_hat": {
            True:  "¿Lleva sombrero o gorra?",
            False: "¿No lleva sombrero ni gorra?",
        },
        "has_beard": {
            True:  "¿Tiene barba?",
            False: "¿No tiene barba?",
        },
        "has_mustache": {
            True:  "¿Tiene bigote?",
            False: "¿No tiene bigote?",
        },
        "skin_tone": {
            "light":  "¿Tiene piel clara?",
            "medium": "¿Tiene piel trigueña?",
            "dark":   "¿Tiene piel oscura?",
        },
        "paso_segunda_vuelta": {
            True:  "¿Tu candidato/a NO se quemó en primera vuelta?",
            False: "¿Tu candidato/a se quemó en primera vuelta?",
        },
        "fue_alcalde": {
            True:  "¿Tu candidato/a fue alcalde o alcaldesa?",
            False: "¿Tu candidato/a nunca fue alcalde ni alcaldesa?",
        },
        "fue_presidente": {
            True:  "¿Tu candidato/a ha sido presidente/a de Colombia?",
            False: "¿Tu candidato/a nunca ha sido presidente/a de Colombia?",
        },
    }
